site_name: Etharialle
theme:
  name: 'mkdocs'
  custom_dir: 'themes/etharialle'

use_directory_urls: true

extra_css:
- css/etharialle.css

nav:
  - Home: index.md
  - Leet Code Snippts: leetcode-snippets.md